// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CellKind.
const (
	CellKindCode     CellKind = "code"
	CellKindMarkdown CellKind = "markdown"
)

// Valid indicates whether the value is a known member of the CellKind enum.
func (e CellKind) Valid() bool {
	switch e {
	case CellKindCode:
		return true
	case CellKindMarkdown:
		return true
	default:
		return false
	}
}

// Defines values for CreateCellRequestKind.
const (
	CreateCellRequestKindCode     CreateCellRequestKind = "code"
	CreateCellRequestKindMarkdown CreateCellRequestKind = "markdown"
)

// Valid indicates whether the value is a known member of the CreateCellRequestKind enum.
func (e CreateCellRequestKind) Valid() bool {
	switch e {
	case CreateCellRequestKindCode:
		return true
	case CreateCellRequestKindMarkdown:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	CsrfInvalid        ErrorCode = "csrf_invalid"
	Internal           ErrorCode = "internal"
	InvalidCredentials ErrorCode = "invalid_credentials"
	LoginTaken         ErrorCode = "login_taken"
	NotFound           ErrorCode = "not_found"
	NotImplemented     ErrorCode = "not_implemented"
	Unauthorized       ErrorCode = "unauthorized"
	ValidationError    ErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case CsrfInvalid:
		return true
	case Internal:
		return true
	case InvalidCredentials:
		return true
	case LoginTaken:
		return true
	case NotFound:
		return true
	case NotImplemented:
		return true
	case Unauthorized:
		return true
	case ValidationError:
		return true
	default:
		return false
	}
}

// Cell Блок блокнота
type Cell struct {
	// Id ID блока внутри блокнота
	Id string `json:"id"`

	// Kind Вид блока
	Kind CellKind `json:"kind"`

	// Source Содержимое блока
	Source string `json:"source"`
}

// CellKind Вид блока
type CellKind string

// CreateCellRequest defines model for CreateCellRequest.
type CreateCellRequest struct {
	// Index Позиция нового блока, с нуля. Без поля блок добавляется в конец
	Index *int `json:"index,omitempty"`

	// Kind Вид блока
	Kind CreateCellRequestKind `json:"kind"`
}

// CreateCellRequestKind Вид блока
type CreateCellRequestKind string

// CreateNotebookRequest defines model for CreateNotebookRequest.
type CreateNotebookRequest struct {
	Name string `json:"name"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// Notebook Блокнот (.ipynb)
type Notebook struct {
	// Cells Блоки в порядке блокнота
	Cells     []Cell    `json:"cells"`
	CreatedAt time.Time `json:"created_at"`

	// Id ID
	Id int64 `json:"id"`

	// Name Название блокнота
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

// NotebookSummary defines model for NotebookSummary.
type NotebookSummary struct {
	// CellsCount Число блоков
	CellsCount int       `json:"cells_count"`
	Id         int64     `json:"id"`
	Name       string    `json:"name"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// User defines model for User.
type User struct {
	// Id ID
	Id    int64  `json:"id"`
	Login string `json:"login"`
}

// Forbidden defines model for Forbidden.
type Forbidden = Error

// LoginUserParams defines parameters for LoginUser.
type LoginUserParams struct {
	// XCSRFToken Значение cookie __Host-csrf
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// LogoutUserParams defines parameters for LogoutUser.
type LogoutUserParams struct {
	// XCSRFToken Значение cookie __Host-csrf
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`

	// RefreshToken Refresh-токен (HttpOnly-cookie, Path=/api/v1/auth)
	RefreshToken string `form:"refresh_token" json:"refresh_token"`
}

// RefreshTokenParams defines parameters for RefreshToken.
type RefreshTokenParams struct {
	// XCSRFToken Значение cookie __Host-csrf
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`

	// RefreshToken Refresh-токен (HttpOnly-cookie, Path=/api/v1/auth)
	RefreshToken string `form:"refresh_token" json:"refresh_token"`
}

// RegisterUserParams defines parameters for RegisterUser.
type RegisterUserParams struct {
	// XCSRFToken Значение cookie __Host-csrf
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// CreateNotebookParams defines parameters for CreateNotebook.
type CreateNotebookParams struct {
	// XCSRFToken Значение cookie __Host-csrf
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// CreateCellParams defines parameters for CreateCell.
type CreateCellParams struct {
	// XCSRFToken Значение cookie __Host-csrf
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// DeleteCellParams defines parameters for DeleteCell.
type DeleteCellParams struct {
	// XCSRFToken Значение cookie __Host-csrf
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = Credentials

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = Credentials

// CreateNotebookJSONRequestBody defines body for CreateNotebook for application/json ContentType.
type CreateNotebookJSONRequestBody = CreateNotebookRequest

// CreateCellJSONRequestBody defines body for CreateCell for application/json ContentType.
type CreateCellJSONRequestBody = CreateCellRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// LoginUser Вход
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request, params LoginUserParams)
	// LogoutUser Выход
	// (POST /auth/logout)
	LogoutUser(w http.ResponseWriter, r *http.Request, params LogoutUserParams)
	// RefreshToken Обновление токенов
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request, params RefreshTokenParams)
	// RegisterUser Регистрация
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request, params RegisterUserParams)
	// ListNotebooks Список блокнотов
	// (GET /notebooks)
	ListNotebooks(w http.ResponseWriter, r *http.Request)
	// CreateNotebook Создание блокнота
	// (POST /notebooks)
	CreateNotebook(w http.ResponseWriter, r *http.Request, params CreateNotebookParams)
	// GetNotebook Блокнот
	// (GET /notebooks/{id})
	GetNotebook(w http.ResponseWriter, r *http.Request, id int64)
	// CreateCell Добавление блока
	// (POST /notebooks/{id}/cells)
	CreateCell(w http.ResponseWriter, r *http.Request, id int64, params CreateCellParams)
	// DeleteCell Удаление блока
	// (DELETE /notebooks/{id}/cells/{index})
	DeleteCell(w http.ResponseWriter, r *http.Request, id int64, index int, params DeleteCellParams)
	// GetCurrentUser Текущий пользователь
	// (GET /users/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginUserParams

	headers := r.Header

	// ------------- Optional header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = &XCSRFToken

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutUserParams

	headers := r.Header

	// ------------- Optional header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = &XCSRFToken

	}

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refresh_token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh_token", Err: err})
				return
			}
			params.RefreshToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "refresh_token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutUser(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshTokenParams

	headers := r.Header

	// ------------- Optional header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = &XCSRFToken

	}

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refresh_token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh_token", Err: err})
				return
			}
			params.RefreshToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "refresh_token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterUserParams

	headers := r.Header

	// ------------- Optional header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = &XCSRFToken

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNotebooks operation middleware
func (siw *ServerInterfaceWrapper) ListNotebooks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotebooks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNotebook operation middleware
func (siw *ServerInterfaceWrapper) CreateNotebook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateNotebookParams

	headers := r.Header

	// ------------- Optional header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = &XCSRFToken

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNotebook(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNotebook operation middleware
func (siw *ServerInterfaceWrapper) GetNotebook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNotebook(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCell operation middleware
func (siw *ServerInterfaceWrapper) CreateCell(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCellParams

	headers := r.Header

	// ------------- Optional header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = &XCSRFToken

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCell(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCell operation middleware
func (siw *ServerInterfaceWrapper) DeleteCell(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "index" -------------
	var index int

	err = runtime.BindStyledParameterWithOptions("simple", "index", mux.Vars(r)["index"], &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteCellParams

	headers := r.Header

	// ------------- Optional header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = &XCSRFToken

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCell(w, r, id, index, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/auth/register", wrapper.RegisterUser).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/auth/login", wrapper.LoginUser).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/auth/refresh", wrapper.RefreshToken).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/auth/logout", wrapper.LogoutUser).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/users/me", wrapper.GetCurrentUser).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/notebooks/{id}/cells", wrapper.CreateCell).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/notebooks/{id}", wrapper.GetNotebook).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/notebooks", wrapper.ListNotebooks).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/notebooks", wrapper.CreateNotebook).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/notebooks/{id}/cells/{index}", wrapper.DeleteCell).Methods(http.MethodDelete)

	return r
}

type ForbiddenJSONResponse Error

type LoginUserRequestObject struct {
	Params LoginUserParams
	Body   *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200ResponseHeaders struct {
	SetCookie *string
}

type LoginUser200JSONResponse struct {
	Body    User
	Headers LoginUser200ResponseHeaders
}

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser400JSONResponse Error

func (response LoginUser400JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser401JSONResponse Error

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response LoginUser403JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser500JSONResponse Error

func (response LoginUser500JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutUserRequestObject struct {
	Params LogoutUserParams
}

type LogoutUserResponseObject interface {
	VisitLogoutUserResponse(w http.ResponseWriter) error
}

type LogoutUser204ResponseHeaders struct {
	SetCookie *string
}

type LogoutUser204Response struct {
	Headers LogoutUser204ResponseHeaders
}

func (response LogoutUser204Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type LogoutUser401JSONResponse Error

func (response LogoutUser401JSONResponse) VisitLogoutUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response LogoutUser403JSONResponse) VisitLogoutUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutUser500JSONResponse Error

func (response LogoutUser500JSONResponse) VisitLogoutUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Params RefreshTokenParams
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken204ResponseHeaders struct {
	SetCookie *string
}

type RefreshToken204Response struct {
	Headers RefreshToken204ResponseHeaders
}

func (response RefreshToken204Response) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type RefreshToken401JSONResponse Error

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken403JSONResponse struct{ ForbiddenJSONResponse }

func (response RefreshToken403JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken500JSONResponse Error

func (response RefreshToken500JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUserRequestObject struct {
	Params RegisterUserParams
	Body   *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201ResponseHeaders struct {
	SetCookie *string
}

type RegisterUser201JSONResponse struct {
	Body    User
	Headers RegisterUser201ResponseHeaders
}

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser400JSONResponse Error

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response RegisterUser403JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser409JSONResponse Error

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser500JSONResponse Error

func (response RegisterUser500JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotebooksRequestObject struct {
}

type ListNotebooksResponseObject interface {
	VisitListNotebooksResponse(w http.ResponseWriter) error
}

type ListNotebooks200JSONResponse []NotebookSummary

func (response ListNotebooks200JSONResponse) VisitListNotebooksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotebooks401JSONResponse Error

func (response ListNotebooks401JSONResponse) VisitListNotebooksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListNotebooks500JSONResponse Error

func (response ListNotebooks500JSONResponse) VisitListNotebooksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNotebookRequestObject struct {
	Params CreateNotebookParams
	Body   *CreateNotebookJSONRequestBody
}

type CreateNotebookResponseObject interface {
	VisitCreateNotebookResponse(w http.ResponseWriter) error
}

type CreateNotebook201JSONResponse Notebook

func (response CreateNotebook201JSONResponse) VisitCreateNotebookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNotebook400JSONResponse Error

func (response CreateNotebook400JSONResponse) VisitCreateNotebookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNotebook401JSONResponse Error

func (response CreateNotebook401JSONResponse) VisitCreateNotebookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNotebook403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateNotebook403JSONResponse) VisitCreateNotebookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNotebook500JSONResponse Error

func (response CreateNotebook500JSONResponse) VisitCreateNotebookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNotebookRequestObject struct {
	Id int64 `json:"id"`
}

type GetNotebookResponseObject interface {
	VisitGetNotebookResponse(w http.ResponseWriter) error
}

type GetNotebook200JSONResponse Notebook

func (response GetNotebook200JSONResponse) VisitGetNotebookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNotebook400JSONResponse Error

func (response GetNotebook400JSONResponse) VisitGetNotebookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetNotebook401JSONResponse Error

func (response GetNotebook401JSONResponse) VisitGetNotebookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetNotebook404JSONResponse Error

func (response GetNotebook404JSONResponse) VisitGetNotebookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetNotebook500JSONResponse Error

func (response GetNotebook500JSONResponse) VisitGetNotebookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCellRequestObject struct {
	Id     int64 `json:"id"`
	Params CreateCellParams
	Body   *CreateCellJSONRequestBody
}

type CreateCellResponseObject interface {
	VisitCreateCellResponse(w http.ResponseWriter) error
}

type CreateCell201JSONResponse Cell

func (response CreateCell201JSONResponse) VisitCreateCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCell400JSONResponse Error

func (response CreateCell400JSONResponse) VisitCreateCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCell401JSONResponse Error

func (response CreateCell401JSONResponse) VisitCreateCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCell403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateCell403JSONResponse) VisitCreateCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCell404JSONResponse Error

func (response CreateCell404JSONResponse) VisitCreateCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCell409JSONResponse Error

func (response CreateCell409JSONResponse) VisitCreateCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCell500JSONResponse Error

func (response CreateCell500JSONResponse) VisitCreateCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCellRequestObject struct {
	Id     int64 `json:"id"`
	Index  int   `json:"index"`
	Params DeleteCellParams
}

type DeleteCellResponseObject interface {
	VisitDeleteCellResponse(w http.ResponseWriter) error
}

type DeleteCell204Response struct {
}

func (response DeleteCell204Response) VisitDeleteCellResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCell400JSONResponse Error

func (response DeleteCell400JSONResponse) VisitDeleteCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCell401JSONResponse Error

func (response DeleteCell401JSONResponse) VisitDeleteCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCell403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteCell403JSONResponse) VisitDeleteCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCell404JSONResponse Error

func (response DeleteCell404JSONResponse) VisitDeleteCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCell500JSONResponse Error

func (response DeleteCell500JSONResponse) VisitDeleteCellResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse User

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUser401JSONResponse Error

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUser500JSONResponse Error

func (response GetCurrentUser500JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// LoginUser Вход
	// (POST /auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// LogoutUser Выход
	// (POST /auth/logout)
	LogoutUser(ctx context.Context, request LogoutUserRequestObject) (LogoutUserResponseObject, error)
	// RefreshToken Обновление токенов
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// RegisterUser Регистрация
	// (POST /auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// ListNotebooks Список блокнотов
	// (GET /notebooks)
	ListNotebooks(ctx context.Context, request ListNotebooksRequestObject) (ListNotebooksResponseObject, error)
	// CreateNotebook Создание блокнота
	// (POST /notebooks)
	CreateNotebook(ctx context.Context, request CreateNotebookRequestObject) (CreateNotebookResponseObject, error)
	// GetNotebook Блокнот
	// (GET /notebooks/{id})
	GetNotebook(ctx context.Context, request GetNotebookRequestObject) (GetNotebookResponseObject, error)
	// CreateCell Добавление блока
	// (POST /notebooks/{id}/cells)
	CreateCell(ctx context.Context, request CreateCellRequestObject) (CreateCellResponseObject, error)
	// DeleteCell Удаление блока
	// (DELETE /notebooks/{id}/cells/{index})
	DeleteCell(ctx context.Context, request DeleteCellRequestObject) (DeleteCellResponseObject, error)
	// GetCurrentUser Текущий пользователь
	// (GET /users/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(w http.ResponseWriter, r *http.Request, params LoginUserParams) {
	var request LoginUserRequestObject

	request.Params = params

	var body LoginUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutUser operation middleware
func (sh *strictHandler) LogoutUser(w http.ResponseWriter, r *http.Request, params LogoutUserParams) {
	var request LogoutUserRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutUser(ctx, request.(LogoutUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutUserResponseObject); ok {
		if err := validResponse.VisitLogoutUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request, params RefreshTokenParams) {
	var request RefreshTokenRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(w http.ResponseWriter, r *http.Request, params RegisterUserParams) {
	var request RegisterUserRequestObject

	request.Params = params

	var body RegisterUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListNotebooks operation middleware
func (sh *strictHandler) ListNotebooks(w http.ResponseWriter, r *http.Request) {
	var request ListNotebooksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListNotebooks(ctx, request.(ListNotebooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNotebooks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListNotebooksResponseObject); ok {
		if err := validResponse.VisitListNotebooksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateNotebook operation middleware
func (sh *strictHandler) CreateNotebook(w http.ResponseWriter, r *http.Request, params CreateNotebookParams) {
	var request CreateNotebookRequestObject

	request.Params = params

	var body CreateNotebookJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateNotebook(ctx, request.(CreateNotebookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateNotebook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateNotebookResponseObject); ok {
		if err := validResponse.VisitCreateNotebookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNotebook operation middleware
func (sh *strictHandler) GetNotebook(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetNotebookRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNotebook(ctx, request.(GetNotebookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNotebook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNotebookResponseObject); ok {
		if err := validResponse.VisitGetNotebookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCell operation middleware
func (sh *strictHandler) CreateCell(w http.ResponseWriter, r *http.Request, id int64, params CreateCellParams) {
	var request CreateCellRequestObject

	request.Id = id
	request.Params = params

	var body CreateCellJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCell(ctx, request.(CreateCellRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCell")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCellResponseObject); ok {
		if err := validResponse.VisitCreateCellResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCell operation middleware
func (sh *strictHandler) DeleteCell(w http.ResponseWriter, r *http.Request, id int64, index int, params DeleteCellParams) {
	var request DeleteCellRequestObject

	request.Id = id
	request.Index = index
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCell(ctx, request.(DeleteCellRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCell")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCellResponseObject); ok {
		if err := validResponse.VisitDeleteCellResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FpbbxvHFf4ri2kebHQpkraaJgT6kMpxkiJIAytFiwoqseKOpI32ltlZx4qwgEi3iQsFECQUKFAgddM+",
	"9JWWxYiWRPovnPlHxZnh3sglRTUSbTl8Ivc2c86Z833nMrNDGp7jey51eUBqO4TRwPfcgMqL+x5bs0yT",
	"unjR8FxOXY5/Dd+3rYbBLc8tfx548jF9ZDi+rb57X/2vLy0/+ACvg9BxDLZNavknOnlo2CFVg5uU1Egj",
	"YOt1y31o2JZJdOLQIDA28MHS8oP7JdGCPpxCB3oa9KCjwUuxC33xRBzA2eACjqAjduFUPCZRFOkkaGxS",
	"x8AZ3mJ0ndTIz8qpvmX1NCi/z5jH1AcmDRrM8lG1/3faeFZpiiVq2/ibHxcO4AwH1eCZ+gM96IsWtIlO",
	"fOb5lHFLmdIyR7/+6F76XVuDI+iJx6IldqFbNJ5jPPqYuht8k9TeXtSJY7nxZVUnvsE5ZTjon1aM0lfv",
	"lf5YKb1bL63+/C2iE77tU1IjAWeWu0EinWxZboE4cAhdOM6IRHRC3dAhtRW1rigD2zK9L12yWjBq4IWs",
	"QQvG/R76cCwN+wN04Rz60MnPMjRUpBNGvwgtRk2cW7qQFDmZI53eW/ucNjhOv8SowSmu0wP6RUgD5eGm",
	"aaEYhv1pZjnWDTugIyvkmvRRgfRPoQ8n0BVfQ1fso+egl/ThOfQzSuiaaGq4fnAm9hc0OIAOnGjwEvp4",
	"I3lRg2PowzNowxHeh45oiSY+P9LgFProluJrIhfXctDylURRy+V0g7LrWr4hm8spxlv5E4/TNc/bylg6",
	"b0zXcKQnZJy2euedYa+dLIMcY4wMJnW5ZdjB6My2t2G5Q1PfvZOb+e44vIyBi28EwZceM4dG/WV+1Hcu",
	"0kdJlhmuSDdFYSNaKV7dSRZUMqsk7jqVX+hkQLf1RsY6upq0zo0tilOHrhHyTY9ZX1FEk+vx+roXuvF/",
	"CzndoS6XT9HjmGvYRM/zeRH2E4bfucAIsScO3i8yQexc4+lWsaJ2a8Hyt9212yNk26C2HUz4vCsB9xL6",
	"YlfswzEGhSLGtTh1gotijgwMUaKGwZixjdcNCRSzbkh0rHvMwX/ENDgtccuhRY5WHCSInn5uufztxSxB",
	"VIsIIkbfkPrfQRtO4Aja0INuscojIoW+eUk1ithbCqQP1iVnm9wMk7xhOc49dooWu97wQpcX6Pxf6Iom",
	"qplq24cjUmQ1y8ypeDlTX6/hMoPpOYWLLPa7gBYwyFX5VsKvU0iv3h2VEZMF2giZxbeXEUZKwjVqMMre",
	"C/lmenU/Fu43v/+MDBIyHEk9TW24ybmvEj/LXfekeBa38ck9um6ENtcczwxttOVDygKlfnWhslBBnTyf",
	"uoZvkRq5u1BdqEiO5ptSqDISZjlR2vdUtEPLSvr9yCQ18jE+lmbHL5nhUE5ZQGorI+74d+hBW3wDnQEE",
	"G563ZVGtXv/QC3gJaZbocQpOakSyMKpHDZOy2B9q5A8lmdF+5ilaT7Pj4UVZVatCA/5rz9yeIv2fLtHO",
	"RuAov/SchTTS8/XHnUrlyqaWZi5I8eFQ/AXzTA2OxJ5KvDCdgp6u7hwj7Yk9La0CxB7RB5aVUi5TXlqS",
	"61GUwyJBwhF0RUszGg0aBHWO1tegqzG6zmiwqW4sTFwPlHvxCq0xtuKB76Ajqf4Ms0JUFl5ocALtQdXT",
	"JFKS6mwkES0NrYe2x/IG5cB8GrpKirvjBk+8qJyWsJFOfjETCx4m9RiitSf2MVHviyfQhWcyv87yGKmt",
	"rOqZAjl2R6ITbmwgFxBkErKKHyWk4oV8Iqt4IZ+GVh4oB8xWuLc+5Nz/rWtvlxTF6NqnBt/8VdnwrfLD",
	"qhTgdiHVqNdTqsk5NxlG+iRf118P9svx0GJhedoRTdGU5Z14LIniTIrY1mMJJZ88h7Z4oh5MTxzq/mTK",
	"kLVjVzRFSxzAqXSwc000xe4gXTmfglLmQL4+IO9dCOXBco7H8gChscvO0XxtaD7MxHrVrBF70MmFfWzW",
	"YDgXuzIqslF75/H+qtKEOaavC9P/hGeDRt5Z4r7p8scV4liwb1gBp2wS2tUb85JgQklQvf6S4Klsv34L",
	"J3Kp26IFHbzWRFP2dCVNzMuDCeXBZbG/WHl3BrL/Azvl4s9S9lPRuimk8y/owPNBnrerOFbsF/OMO2h6",
	"ScfboEXFgRXwT5K3fmS9PVWjc7gRN9LzLDBYrl+r0NXB3TXxV2mLfrxDMgzR/denOn09PSvfLVtZjfKu",
	"9j28lH3Pgq3JfGxLHW010sdEs/yWz08onhVsdM04siVGvxBcuZhG5l2mNzaRvRD5iReM3eMpwH4u6JR3",
	"LDMaG3k+oHw8F4ziGjvpKarltsD4ovNSexEFBWHlFSBvDrYisC3ORgos8dvwAo+X4GrcWNjmPWpajJaT",
	"je5JkVvuUF8QtbNHkVKmmCma9Tc7k8geTJpxFqGOKIznsdypJLT2nNKuIn94lSQ4m0L8cJg0OriB8gNK",
	"dA5tOMVNFfkPK7yePPcnvik8kKHdqlYqlds3lr//lgdQPvVqX5LQyzvyLGKk+kw25XSU2u/J+zeW2p9m",
	"zl6pFv0L1a0/x3Oi+WOxI06WO2w5jS5ozYnqTDpveWN2PmI2j/cwxcGcyW8+k99IOvxPZhd9aioMA8qC",
	"skMnVZ5LIWPUjQ9FzP6Q0b+T/mUXXozrXn47717+KO+Z0sipJ0nPQS+KknvxEXTVVY/05Fq9m7mRumG0",
	"Gv1vAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
